### ISSUE TITLE
Finish the instructions bro?!

### ISSUE THREAD

**Issue by NSExceptional** [ParasiteTeam/documentation#1]
This looks really cool! I wanna know how to get set up with making bundles without just copying one of the example projects and guessing at how they work...

**Comment by shinvou** [comment]
a) Use our Xcode template or
b) do it manually. Create a new bundle in Xcode, link ParasiteRuntime, add your Filter to the Info.plist.

**Comment by NSExceptional** [comment]
Gotcha, thanks. Should still add that to the docs though ;)

**Comment by shinvou** [comment]
ATM I have university test phase, I don't have time for anything Parasite related. After that I will actually continue working on this, release v1 and update the documentation.

**Comment by NSExceptional** [comment]
Gotcha, okay.
