### ISSUE TITLE
Can I inject code statically into an app?

### ISSUE THREAD

**Issue by Geri-Borbas** [ParasiteTeam/documentation#2]
I have a closed source built OSX app (a Unity Player actually), now I just want to **statically inject some functionality to the executable**. I have the classes dumped at https://github.com/eppz/Unity.Labs.OSX_Unity_Player_Headers

Can I do this with Parasite?
Is there any other tool out there to statically patch app executables?

**Comment by alexzielenski** [comment]
Try https://github.com/alexzielenski/optool
